apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app-chart.fullname" . }}
  labels:
    app: {{ include "my-app-chart.name" . }}
spec:
  selector:
    app: {{ include "my-app-chart.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP